### ISSUE TITLE
How can I do more advanced things using the theorem-prover

### ISSUE THREAD

**Issue by LenniDev** [teknomo/theorem-prover#2]
I noticed that when I am playing around with the theorem prover I am running into a few problems, for example that when I try following 
```
thp.prove([
    "axiom forall x,y,k. Equals(x,y) implies Equals(k(x),k(y))",
    "Equals(2,3) implies Equals(s(2),s(3))",
])
```
it cant prove the last statement which I think should be provable.
Also I cant state the Axiom of extensionality like this:
`axiom forall n, Phi. (exists x. (forall y. (In(y,x) implies Phi(y)) and (Phi(y) implies In(y,x))))`
I have a few other minor Problems, but just wanted to ask If and how you could do stuff like this.

**Comment by teknomo** [comment]
For this version, the built-in function `Equals(x, y)` only accept variable term (small letter), not user-defined-function yet. If you have more than one variable, write it separate for all. For example:
`'axiom forall x. forall y. Equals(x, y) implies Equals(y,x)'` works.
Your k is user-defined function, therefore you need to write in capital letter.

Example:
```
statement=[
    'axiom forall x. F(x) implies G(x)',
    'axiom forall x. forall y. Equals(x, y) implies Equals(y,x)',
    'lemma exists x. forall y. F(x) implies G(y)'
]
thp.prove(statement)

```
